# # This GitLab CI configuration is used for the project of "Tampere Adventure"

# # For more information refer to https://course-gitlab.tuni.fi/help/ci/README.md
# # We use an image based on Alpine Linux that contains
# # Qt 5.14.2 and the necessary stuff

# image: honksu/new-qt:5142

# # The stages of our current pipeline
# stages:
#   - build
#   - test


# # Build job for gameview's unit test for the game gogogo-"Tampere Adventure"
# Gameview:
#   # The runner must be able to run and compile Qt projects
#   tags:
#     - qt
#   # Build jobs naturally go to the build stage
#   # We could also have multi-stage builds if needed
#   stage: build
#   # The command line commands we want the CI environment to execute
#   # When the script section starts, the working directory is the repository's root
#   script: 
#     # Go to the correct directory
#     - cd UnitTest/gameview
#     ##try to add Qt multimedia
#     - bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" >> /etc/apt/sources.list'
#     - add-apt-repository universe
#     - add-apt-repository multiverse
#     - apt-get update
#     #test
#     - apt-get build-dep qtmultimedia5-dev
#     - apt-get source --compile qtmultimedia5-dev
#     # Run qmake to produce the makefile
#     - qmake
#     # Compile the project using the generated Makefile
#     - make
#     # Clean up the build
#     - make clean
#   # In a distributed CI system we need a way to pass the generated binary between jobs.
#   # GitLab CI provides artifacts to achieve this.
#   artifacts:
#     # Paths to the artifacts we want to pass
#     paths:
#       - UnitTests/gameview/gameviewtest
#     # How long we store the artifacts in GitLab
#     expire_in: 30d

# # Test job for gameview's unit test in gogogo
# GameviewTest:
#   tags:
#     - qt
#   stage: test
#   script:
#     # Go to the correct directory
#     - cd UnitTests/gameview
#     # Run the test binary
#     - ./gameviewtest
#   # On what jobs this dependes on, which artifacts we download for this job
#   dependencies:
#     - Gameview

#
